### ISSUE TITLE
Questions about use of intel PT

### ISSUE THREAD

**Issue by qunqunqun** [carter-yagemann/ARCUS#5]
The wonderful paper "Automated Bug Hunting With Data-Driven Symbolic Root Cause Analysis" introduce using intel PT to get information like control flow. But like [perf](https://perf.wiki.kernel.org/index.php/Perf_tools_support_for_Intel%C2%AE_Processor_Trace) says," Intel PT can potentially produce hundreds of megabytes of trace data per CPU per second. That can be at a faster rate than it can be recorded to file (resulting in trace data loss), and sometimes faster even than can be recording to memory (resulting in overflow packets)". I am wondering if the data lost problem exist while tracing in your experiment and how you solve it if it does exists. Or the algorithm can allow little loss of data? 
Thank you and hoping for your answer!

**Comment by carter-yagemann** [comment]
This is a very good question and one that comes up a lot.

If you use ARCUS right now with the Perf trace collection, it can lose data both at the hardware level (overflow packets) and software level (Perf deciding to throw away a buffer). If you use the Griffin trace collection, there's only hardware data loss (Griffin will buffer to memory as much as it has to, though it's still possible to run out and then you're in trouble).

In practice, no data loss was observed in any of our real-world datasets. The traces we collected where short enough and/or the programs blocked frequently enough (syscalls, I/O, etc.) to give PT enough time to flush.

In theory, because overflow packets are followed by a packet generation enable (PGE) packet, which provides an instruction pointer (IP), you could attempt to "plug the hole" using symbolic analysis to explore and recover feasible paths, but this is beyond the current scope of ARCUS.

According to Intel documentation, PT can also output to TraceHub, which can back-pressure the CPU to prevent data loss, however we have not investigated this because there isn't much documentation on what hardware is TraceHub compatible or how to use it.
