### ISSUE TITLE
[Question] Question about the system requirements

### ISSUE THREAD

**Issue by lh-ycx** [carter-yagemann/ARCUS#7]
Hi, thanks for the excellent work! After reading the paper, I do want to try ARCUS by myself. Meanwhile, I notice that the system requirements are missing in the paper as well as in the document. So I submit this issue to ask for the detailed system requirements.

FYI, I tried to build and install ARCUS according to the [instructions](https://github.com/carter-yagemann/ARCUS/blob/master/docs/griffin-setup.md) on my _ubuntu20.04 with the 5.4.0 Linux kernel, equipped with Xeon E5-4620 v2 @ 2.60GHz_ (which should support intel PT). I failed to set up Griffin in the step `sudo make INSTALL_MOD_STRIP=1 install`, getting the following output:

arch/x86/Makefile:123: stack-protector enabled but compiler support broken
sh ./arch/x86/boot/install.sh 4.2.0 arch/x86/boot/bzImage \
        System.map "/boot"
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 4.2.0 /boot/vmlinuz-4.2.0
run-parts: executing /etc/kernel/postinst.d/dkms 4.2.0 /boot/vmlinuz-4.2.0
 \* dkms: running auto installation service for kernel 4.2.0                           [ OK ]
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 4.2.0 /boot/vmlinuz-4.2.0
update-initramfs: Generating /boot/initrd.img-4.2.0
**modinfo: ERROR: could not get modinfo from 'crc32': No such file or directory**
run-parts: executing /etc/kernel/postinst.d/unattended-upgrades 4.2.0 /boot/vmlinuz-4.2.0
run-parts: executing /etc/kernel/postinst.d/update-notifier 4.2.0 /boot/vmlinuz-4.2.0
run-parts: executing /etc/kernel/postinst.d/xx-update-initrd-links 4.2.0 /boot/vmlinuz-4.2.0
run-parts: executing /etc/kernel/postinst.d/zz-update-grub 4.2.0 /boot/vmlinuz-4.2.0
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/init-select.cfg'
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.4.0-107-generic
Found initrd image: /boot/initrd.img-5.4.0-107-generic
Found linux image: /boot/vmlinuz-5.4.0-105-generic
Found initrd image: /boot/initrd.img-5.4.0-105-generic
Found linux image: /boot/vmlinuz-5.4.0-104-generic
Found initrd image: /boot/initrd.img-5.4.0-104-generic
Found linux image: /boot/vmlinuz-4.2.0
Found initrd image: /boot/initrd.img-4.2.0
Found linux image: /boot/vmlinuz-4.2.0.old
Found initrd image: /boot/initrd.img-4.2.0
done

It seems that Griffin will interact with kernel 4.2.0. So I wonder if I need to use a system with kernel 4.2.0.

**Comment by carter-yagemann** [comment]
Hi @lh-ycx :wave: 

### GRIFFIN compile error

To my knowledge, the [upstream](https://github.com/TJAndHisStudents/Griffin-Trace) researchers no longer maintain GRIFFIN, so it's slowly incurring bit rot. Porting to a newer version of Linux is (unfortunately) not easy. Your options are:

1. Use Debian Stretch or Buster (not Bullseye) as your base OS to compile and install GRIFFIN on. I have done this myself and it should work. Let me know if it fails.
2. Use the [Perf tracing interface](https://github.com/carter-yagemann/ARCUS/blob/master/docs/perf.md) instead. This should work on just about any Linux kernel version. The only reason it's not the preferred tracer right now is because it can drop the tail-end of a trace when the program being traced terminates with a crash (which is annoying if you want to analyze a PoC, for bug hunting starting from non-crashing inputs, this is not an issue). This seems to be an intrinsic behavior of Perf and outside my control to fix.

Of course, if you or anyone else can figure out the Perf issue or port GRIFFIN forward, I will be forever grateful.

### VM tracing

To my knowledge, there is currently no reliable way to PT trace user space programs that reside inside a virtual machine.

There are some experimental systems out there like hard-forks of KVM, but ARCUS does not support them at this time. _Your best option is to use a physical machine, not a virtual machine._


Thanks for your interest in ARCUS. Let me know if you have further troubles and I will try to help. I will also update the documentation to reflect these details.

**Comment by lh-ycx** [comment]
Thanks for the timely reply. 

I will first try the Perf Tracing Interface, considering that it is officially supported by system vendors. If it fails, I will try the Griffin on Debian Stretch or Buster.  I will update the progress under this issue.

Thanks.
